# Changes here will be overwritten by Copier
_commit: v0.3.3
_src_path: https://github.com/fohte/generic-boilerplate
auto_merge_release_pr: false
binary_name: runok
description: Command execution permission framework for LLM agents
is_public: true
project_name: runok
release_binary: true
release_type: rust
type: rust
use_coverage: true
use_release_please: true
