# Changes here will be overwritten by Copier
_commit: v0.1.27
_src_path: https://github.com/fohte/generic-boilerplate
description: Command execution permission framework for LLM agents
is_public: true
project_name: runok
release_type: rust
type: rust
use_release_please: true
