use std::collections::HashMap;

use crate::adapter::{ActionResult, Endpoint, SandboxInfo};
use crate::audit::AuditMetadata;
use crate::config::{ActionKind, Defaults, MergedSandboxPolicy, SandboxPreset};
use crate::exec::command_executor::{CommandExecutor, CommandInput, SandboxPolicy};
use crate::rules::command_parser::shell_quote_join;
use crate::rules::rule_engine::Action;

/// Sandbox execution wrapper endpoint, invoked internally by hooks via `updatedInput`.
///
/// Receives a command as CLI arguments (`-- <command>`) and evaluates it against
/// the configured rules. Allowed commands are executed via `CommandExecutor`;
/// denied (or ask) commands produce stderr output and exit code 3.
pub struct ExecAdapter {
    args: Vec<String>,
    sandbox_preset: Option<String>,
    /// Set when this invocation was generated by `wrap_with_sandbox` in the
    /// Claude Code hook adapter (`--__hook-origin`), rather than typed by a
    /// user. Only in that case does `Action::Pass` defer to the sandbox
    /// instead of being treated as deny -- the hook already decided to route
    /// the permission decision through Claude Code's own flow.
    ///
    /// This flag is a plain, self-declared CLI argument -- there is no
    /// cryptographic proof that a given invocation actually came from the
    /// hook. Anyone who can run `runok exec` at all can set it. This is
    /// deliberately not treated as a security hole: it only relaxes
    /// `Action::Pass` (a command that matched no rule), never `Action::Deny`
    /// or `Action::Ask`, both of which `exec` still re-evaluates and rejects
    /// regardless of this flag. So spoofing it can only turn "the caller's
    /// own permission flow decides, unsandboxed" into "the caller's own
    /// permission flow decides, sandboxed" -- a strictly narrower outcome,
    /// not a privilege escalation.
    hook_origin: bool,
    sandbox_definitions: HashMap<String, SandboxPreset>,
    executor: Box<dyn CommandExecutor>,
}

impl ExecAdapter {
    pub fn new(
        args: Vec<String>,
        sandbox_preset: Option<String>,
        executor: Box<dyn CommandExecutor>,
    ) -> Self {
        Self {
            args,
            sandbox_preset,
            hook_origin: false,
            sandbox_definitions: HashMap::new(),
            executor,
        }
    }

    /// Set sandbox preset definitions for resolving preset names to policies.
    pub fn with_sandbox_definitions(mut self, definitions: HashMap<String, SandboxPreset>) -> Self {
        self.sandbox_definitions = definitions;
        self
    }

    /// Mark this invocation as originating from the Claude Code hook wrapper.
    pub fn with_hook_origin(mut self, hook_origin: bool) -> Self {
        self.hook_origin = hook_origin;
        self
    }

    fn command_input(&self) -> CommandInput {
        if self.args.len() == 1 {
            CommandInput::Shell(self.args[0].clone())
        } else {
            CommandInput::Argv(self.args.clone())
        }
    }

    /// Resolve a sandbox preset name to a `SandboxPolicy`.
    fn resolve_sandbox_policy(
        &self,
        preset_name: &str,
    ) -> Result<Option<SandboxPolicy>, anyhow::Error> {
        let preset = match self.sandbox_definitions.get(preset_name) {
            Some(p) => p,
            None => {
                anyhow::bail!(
                    "sandbox preset '{}' is not defined in definitions.sandbox",
                    preset_name
                );
            }
        };

        // `merge_strictest` with a non-empty slice always returns `Some`.
        let Some(merged) = SandboxPreset::merge_strictest(&[preset]) else {
            unreachable!("merge_strictest with a non-empty slice always returns Some");
        };
        let sandbox_policy = SandboxPolicy::from_merged(&merged)?;
        Ok(Some(sandbox_policy))
    }

    /// Build a `SandboxPolicy` from a `MergedSandboxPolicy`.
    fn build_sandbox_policy(merged: &MergedSandboxPolicy) -> Result<SandboxPolicy, anyhow::Error> {
        Ok(SandboxPolicy::from_merged(merged)?)
    }

    /// Resolve `sandbox` to a `SandboxPolicy` and execute the command under it.
    fn execute_with_sandbox(&self, sandbox: &SandboxInfo) -> Result<i32, anyhow::Error> {
        let command_input = self.command_input();

        let policy = match sandbox {
            SandboxInfo::Preset(preset) => {
                let preset_name = preset.as_ref().or(self.sandbox_preset.as_ref());
                match preset_name {
                    Some(name) => self.resolve_sandbox_policy(name)?,
                    None => None,
                }
            }
            SandboxInfo::MergedPolicy(Some(merged)) => Some(Self::build_sandbox_policy(merged)?),
            SandboxInfo::MergedPolicy(None) => None,
        };

        Ok(self.executor.exec(&command_input, policy.as_ref())?)
    }
}

impl Endpoint for ExecAdapter {
    fn extract_command(&self) -> Result<Option<String>, anyhow::Error> {
        if self.args.is_empty() {
            return Ok(None);
        }
        // Return single arguments unquoted so the rule engine can detect
        // shell metacharacters (&&, ;, |) in compound commands.
        if self.args.len() == 1 {
            return Ok(Some(self.args[0].clone()));
        }
        Ok(Some(shell_quote_join(&self.args)?))
    }

    fn handle_action(&self, result: ActionResult) -> Result<i32, anyhow::Error> {
        match result.action {
            Action::Allow => self.execute_with_sandbox(&result.sandbox),
            Action::Deny(deny_response) => {
                if deny_response.matched_rule.is_empty() {
                    eprintln!("runok: command denied by default policy");
                } else {
                    eprintln!("runok: denied: {}", deny_response.matched_rule);
                }
                if let Some(ref message) = deny_response.message {
                    eprintln!("  reason: {}", message);
                }
                if let Some(ref suggestion) = deny_response.fix_suggestion {
                    eprintln!("  suggestion: {}", suggestion);
                }
                Ok(3)
            }
            Action::Ask(message) => {
                // Ask is treated as deny in exec mode
                let msg = message.unwrap_or_else(|| "command requires confirmation".to_string());
                eprintln!("runok: {}", msg);
                Ok(3)
            }
            Action::Pass => {
                if self.hook_origin {
                    // The hook already decided to defer this decision to
                    // Claude Code's own permission flow and resolved the
                    // sandbox to run it under -- honor that instead of
                    // re-asking here.
                    return self.execute_with_sandbox(&result.sandbox);
                }
                // exec has no caller to defer a decision to (unlike the
                // Claude Code hook, there's no "normal permission flow"
                // underneath it) -- treated as deny, same as Ask.
                eprintln!(
                    "runok: command requires confirmation (defaults.action: pass has \
                     no effect outside the Claude Code hook)"
                );
                Ok(3)
            }
        }
    }

    // Unreachable via the CLI: `ExecArgs.command` is `required = true`, so `args` is never empty.
    fn handle_no_match(&self, defaults: &Defaults) -> Result<i32, anyhow::Error> {
        match defaults.resolved_action() {
            ActionKind::Allow => {
                if self.args.is_empty() {
                    return Ok(0);
                }
                let command_input = self.command_input();
                let exit_code = self.executor.exec(&command_input, None)?;
                Ok(exit_code)
            }
            ActionKind::Deny => {
                eprintln!("runok: command denied by default policy");
                Ok(3)
            }
            ActionKind::Ask => {
                // Ask is treated as deny in exec mode
                eprintln!("runok: command requires confirmation (default policy)");
                Ok(3)
            }
            ActionKind::Pass => {
                // exec has no caller to defer to; treated as deny like Ask.
                eprintln!(
                    "runok: command requires confirmation (defaults.action: pass has \
                     no effect outside the Claude Code hook)"
                );
                Ok(3)
            }
        }
    }

    fn handle_error(&self, error: anyhow::Error) -> i32 {
        eprintln!("runok: error: {}", error);
        1
    }

    fn audit_metadata(&self) -> AuditMetadata {
        AuditMetadata {
            endpoint_type: "exec".to_owned(),
            cwd: std::env::current_dir()
                .ok()
                .map(|p| p.to_string_lossy().to_string()),
            ..AuditMetadata::default()
        }
    }

    fn is_auditable(&self) -> bool {
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::exec::ExecError;
    use crate::exec::command_executor::{CommandInput, ExecMode, SandboxPolicy};
    use crate::rules::rule_engine::DenyResponse;
    use rstest::rstest;
    use std::cell::RefCell;

    struct MockExecutor {
        exit_code: i32,
        last_command: RefCell<Option<CommandInput>>,
    }

    impl MockExecutor {
        fn new(exit_code: i32) -> Self {
            Self {
                exit_code,
                last_command: RefCell::new(None),
            }
        }
    }

    impl CommandExecutor for MockExecutor {
        fn exec(
            &self,
            command: &CommandInput,
            _sandbox: Option<&SandboxPolicy>,
        ) -> Result<i32, ExecError> {
            *self.last_command.borrow_mut() = Some(command.clone());
            Ok(self.exit_code)
        }

        fn validate(&self, _command: &[String]) -> Result<(), ExecError> {
            Ok(())
        }

        fn determine_exec_mode(
            &self,
            _sandbox: Option<&SandboxPolicy>,
            _is_compound: bool,
        ) -> ExecMode {
            ExecMode::SpawnAndWait
        }
    }

    struct CapturingExecutor {
        captured: std::sync::Arc<std::sync::Mutex<Option<CommandInput>>>,
    }

    impl CommandExecutor for CapturingExecutor {
        fn exec(
            &self,
            command: &CommandInput,
            _sandbox: Option<&SandboxPolicy>,
        ) -> Result<i32, ExecError> {
            *self.captured.lock().unwrap() = Some(command.clone());
            Ok(0)
        }

        fn validate(&self, _command: &[String]) -> Result<(), ExecError> {
            Ok(())
        }

        fn determine_exec_mode(
            &self,
            _sandbox: Option<&SandboxPolicy>,
            _is_compound: bool,
        ) -> ExecMode {
            ExecMode::SpawnAndWait
        }
    }

    // --- extract_command ---

    #[rstest]
    #[case::empty_args(vec![], None)]
    #[case::single_arg(vec!["git".into()], Some("git".to_string()))]
    #[case::single_compound_arg(
        vec!["echo hello && echo world".into()],
        Some("echo hello && echo world".to_string())
    )]
    #[case::multiple_args(
        vec!["git".into(), "status".into()],
        Some("git status".to_string())
    )]
    #[case::args_with_spaces(
        vec!["echo".into(), "hello world".into()],
        Some("echo 'hello world'".to_string())
    )]
    fn extract_command_returns_expected(
        #[case] args: Vec<String>,
        #[case] expected: Option<String>,
    ) {
        let adapter = ExecAdapter::new(args, None, Box::new(MockExecutor::new(0)));
        let result = adapter.extract_command().unwrap();
        assert_eq!(result, expected);
    }

    // --- handle_action: Allow ---

    #[rstest]
    #[case::exit_0(0)]
    #[case::exit_1(1)]
    #[case::exit_42(42)]
    fn handle_action_allow_executes_and_returns_exit_code(#[case] exit_code: i32) {
        let adapter = ExecAdapter::new(
            vec!["git".into(), "status".into()],
            None,
            Box::new(MockExecutor::new(exit_code)),
        );
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Allow,
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, exit_code);
    }

    #[rstest]
    fn handle_action_allow_with_merged_policy() {
        let adapter = ExecAdapter::new(
            vec!["git".into(), "status".into()],
            Some("default-preset".into()),
            Box::new(MockExecutor::new(0)),
        );
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Allow,
                sandbox: SandboxInfo::MergedPolicy(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, 0);
    }

    #[rstest]
    fn handle_action_allow_errors_on_undefined_sandbox_preset() {
        let adapter = ExecAdapter::new(
            vec!["echo".into(), "hello".into()],
            Some("nonexistent".into()),
            Box::new(MockExecutor::new(0)),
        );
        let result = adapter.handle_action(ActionResult {
            action: Action::Allow,
            sandbox: SandboxInfo::Preset(None),
            evaluations: vec![],
        });
        let err = result.unwrap_err();
        assert!(
            err.to_string().contains("nonexistent"),
            "error should mention the preset name: {}",
            err
        );
    }

    // --- handle_action: Deny ---

    #[rstest]
    fn handle_action_deny_with_fix_suggestion() {
        let adapter = ExecAdapter::new(
            vec!["rm".into(), "-rf".into(), "/".into()],
            None,
            Box::new(MockExecutor::new(0)),
        );
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Deny(DenyResponse {
                    message: Some("dangerous command".to_string()),
                    fix_suggestion: Some("use rm with specific paths".to_string()),
                    matched_rule: "rm -rf /".to_string(),
                }),
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, 3);
    }

    #[rstest]
    #[case::with_message(Some("dangerous command".to_string()))]
    #[case::without_message(None)]
    fn handle_action_deny_returns_exit_3(#[case] message: Option<String>) {
        let adapter = ExecAdapter::new(
            vec!["rm".into(), "-rf".into(), "/".into()],
            None,
            Box::new(MockExecutor::new(0)),
        );
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Deny(DenyResponse {
                    message,
                    fix_suggestion: None,
                    matched_rule: "rm -rf /".to_string(),
                }),
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, 3);
    }

    // `--__hook-origin` only relaxes `Action::Pass` -- a spoofed flag must
    // never let a denied command through. This is the load-bearing guarantee
    // behind treating the flag's forgeability as an accepted risk rather than
    // a security hole (see the doc comment on `ExecAdapter::hook_origin`).
    #[rstest]
    fn handle_action_deny_returns_exit_3_even_with_hook_origin() {
        let adapter = ExecAdapter::new(
            vec!["rm".into(), "-rf".into(), "/".into()],
            None,
            Box::new(MockExecutor::new(0)),
        )
        .with_hook_origin(true);
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Deny(DenyResponse {
                    message: None,
                    fix_suggestion: None,
                    matched_rule: "rm -rf /".to_string(),
                }),
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, 3);
    }

    // --- handle_action: Ask (treated as deny) ---

    #[rstest]
    #[case::with_message(Some("please confirm".to_string()))]
    #[case::without_message(None)]
    fn handle_action_ask_returns_exit_3(#[case] message: Option<String>) {
        let adapter = ExecAdapter::new(
            vec!["terraform".into(), "apply".into()],
            None,
            Box::new(MockExecutor::new(0)),
        );
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Ask(message),
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, 3);
    }

    // Same guarantee as the deny case above, for ask.
    #[rstest]
    fn handle_action_ask_returns_exit_3_even_with_hook_origin() {
        let adapter = ExecAdapter::new(
            vec!["terraform".into(), "apply".into()],
            None,
            Box::new(MockExecutor::new(0)),
        )
        .with_hook_origin(true);
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Ask(Some("please confirm".to_string())),
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, 3);
    }

    // --- handle_action: Pass (treated as deny) ---

    #[rstest]
    fn handle_action_pass_returns_exit_3() {
        let adapter = ExecAdapter::new(
            vec!["terraform".into(), "apply".into()],
            None,
            Box::new(MockExecutor::new(0)),
        );
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Pass,
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, 3);
    }

    // --- handle_action: Pass with hook_origin (executes via sandbox) ---

    #[rstest]
    #[case::exit_0(0)]
    #[case::exit_1(1)]
    #[case::exit_42(42)]
    fn handle_action_pass_with_hook_origin_executes_and_returns_exit_code(#[case] exit_code: i32) {
        let adapter = ExecAdapter::new(
            vec!["terraform".into(), "apply".into()],
            None,
            Box::new(MockExecutor::new(exit_code)),
        )
        .with_hook_origin(true);
        let result = adapter
            .handle_action(ActionResult {
                action: Action::Pass,
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();
        assert_eq!(result, exit_code);
    }

    #[rstest]
    fn handle_action_pass_with_hook_origin_errors_on_undefined_sandbox_preset() {
        let adapter = ExecAdapter::new(
            vec!["echo".into(), "hello".into()],
            Some("nonexistent".into()),
            Box::new(MockExecutor::new(0)),
        )
        .with_hook_origin(true);
        let result = adapter.handle_action(ActionResult {
            action: Action::Pass,
            sandbox: SandboxInfo::Preset(None),
            evaluations: vec![],
        });
        let err = result.unwrap_err();
        assert!(
            err.to_string().contains("nonexistent"),
            "error should mention the preset name: {}",
            err
        );
    }

    // --- handle_no_match ---

    #[rstest]
    #[case::allow_default(Some(ActionKind::Allow), 0, true)]
    #[case::none_default(None, 3, false)]
    #[case::deny_default(Some(ActionKind::Deny), 3, false)]
    #[case::ask_default(Some(ActionKind::Ask), 3, false)]
    #[case::pass_default(Some(ActionKind::Pass), 3, false)]
    fn handle_no_match_follows_defaults(
        #[case] default_action: Option<ActionKind>,
        #[case] expected_exit_code: i32,
        #[case] should_execute: bool,
    ) {
        let executor = std::sync::Arc::new(std::sync::Mutex::new(false));
        let executor_clone = executor.clone();

        struct TrackingExecutor {
            exit_code: i32,
            executed: std::sync::Arc<std::sync::Mutex<bool>>,
        }

        impl CommandExecutor for TrackingExecutor {
            fn exec(
                &self,
                _command: &CommandInput,
                _sandbox: Option<&SandboxPolicy>,
            ) -> Result<i32, ExecError> {
                *self.executed.lock().unwrap() = true;
                Ok(self.exit_code)
            }

            fn validate(&self, _command: &[String]) -> Result<(), ExecError> {
                Ok(())
            }

            fn determine_exec_mode(
                &self,
                _sandbox: Option<&SandboxPolicy>,
                _is_compound: bool,
            ) -> ExecMode {
                ExecMode::SpawnAndWait
            }
        }

        let adapter = ExecAdapter::new(
            vec!["some-command".into()],
            None,
            Box::new(TrackingExecutor {
                exit_code: 0,
                executed: executor_clone,
            }),
        );

        let defaults = Defaults {
            action: default_action,
            sandbox: None,
        };
        let result = adapter.handle_no_match(&defaults).unwrap();
        assert_eq!(result, expected_exit_code);
        assert_eq!(*executor.lock().unwrap(), should_execute);
    }

    #[rstest]
    fn handle_no_match_empty_args_returns_0() {
        let adapter = ExecAdapter::new(vec![], None, Box::new(MockExecutor::new(0)));
        let defaults = Defaults {
            action: Some(ActionKind::Allow),
            sandbox: None,
        };
        let result = adapter.handle_no_match(&defaults).unwrap();
        assert_eq!(result, 0);
    }

    // --- handle_error ---

    #[rstest]
    fn handle_error_returns_exit_1() {
        let adapter = ExecAdapter::new(vec![], None, Box::new(MockExecutor::new(0)));
        let result = adapter.handle_error(anyhow::anyhow!("something went wrong"));
        assert_eq!(result, 1);
    }

    // --- command_input dispatching ---

    #[rstest]
    #[case::single_arg_shell(
        vec!["echo hello && echo world".into()],
        CommandInput::Shell("echo hello && echo world".to_string())
    )]
    #[case::multiple_args_argv(
        vec!["git".into(), "status".into()],
        CommandInput::Argv(vec!["git".into(), "status".into()])
    )]
    fn handle_action_dispatches_correct_command_input(
        #[case] args: Vec<String>,
        #[case] expected: CommandInput,
    ) {
        let executed_command: std::sync::Arc<std::sync::Mutex<Option<CommandInput>>> =
            std::sync::Arc::new(std::sync::Mutex::new(None));

        let adapter = ExecAdapter::new(
            args,
            None,
            Box::new(CapturingExecutor {
                captured: executed_command.clone(),
            }),
        );

        adapter
            .handle_action(ActionResult {
                action: Action::Allow,
                sandbox: SandboxInfo::Preset(None),
                evaluations: vec![],
            })
            .unwrap();

        let captured = executed_command.lock().unwrap();
        assert_eq!(*captured, Some(expected));
    }

    // --- audit metadata ---

    #[rstest]
    fn audit_metadata_returns_exec_endpoint_type() {
        let adapter = ExecAdapter::new(
            vec!["git".into(), "status".into()],
            None,
            Box::new(MockExecutor::new(0)),
        );
        let metadata = adapter.audit_metadata();
        assert_eq!(metadata.endpoint_type, "exec");
        assert!(metadata.cwd.is_some());
        assert!(metadata.session_id.is_none());
        assert!(metadata.tool_name.is_none());
        assert!(metadata.hook_event_name.is_none());
    }

    #[rstest]
    fn is_auditable_returns_true() {
        let adapter = ExecAdapter::new(vec![], None, Box::new(MockExecutor::new(0)));
        assert!(adapter.is_auditable());
    }
}
